### PR TITLE
launching: launch games through protocolls, eg. steam://run/220 to run hl2

### PR DESCRIPTION
**Pull request by pharno**

### CODE REVIEW

**Comment by pharno** [comment]
btw, all styling is gone for me, it looks just like plain html. is this expected?

**Comment by thesbros** [comment]
does shell have to be required through remote?

by styling do you mean syntax highlighting? what editor are you using

**Comment by thesbros** [comment]
merged with style changes & es6 array.includes: add16fdb9105a484ab1820cfcb033e6f916578c5
thanks!

**Comment by thesbros** [comment]
seems the "currently open" breaks with this. will have to check tomorrow

**Comment by pharno** [comment]
no, by styling I mean that the app looks like its plain html. Like all the CSS and images are gone.

what do you mean, shell isnt required through remote?

**Comment by amitkparekh** [comment]
We're in the process of redesigning the entire thing. The old design was based off of what Project Ascension are going to use, but we are going to do something totally different. To make it easier to add the new design when it's finished, we're going to develop the app in just plain old HTML, ot keep things simple.

**Comment by pharno** [comment]
oh allright. I guess that answers my "is that expected" question with yes, thanks.

**Comment by pharno** [comment]
but to be honest, im not sure if I really agree with this decision. I mean sure, focus on the functionality, and not the style, but its also important. Something like this is just shitty looking, and possibly demotivates people to work on it. 

screen shot 2015-04-29 at 18 39 11

Some dev-styling shouldnt be hard to do, especially if a frontend framework is used.  this here didnt take long to do, but is much easier and rewarding to look at.

**Comment by amitkparekh** [comment]
Okay, you misunderstand the reasoning behind that decision. I apologise if that is my fault for not explaining correctly. 

We are working on a complete design overhaul. We have big plans for it but for now, we've decided to remove all styling so that when the design is finalised, we can add the design onto a clean canvas. I personally asked Oden to remove all the design so that I have a blank canvas to work with. 

We are also focusing on the design. We have 3  developers working on the features whilst myself and my colleague are working solely on the design. We are not neglecting the design at all. 

With regards to people being demotivated, we're not going to announce or release it to the public any time soon until we have something stable and well designed. 

And your quick mockup looks like it was just added from something like Materialize or Polymer, which are not going to be using. All the CSS is going to be coded from scratch. 

Hopefully this explains where we're going with this a bit better. Let me know if you have any more questions or anything!

**Comment by Rob--** [comment]
Pharno, although I agree with you, there is a design branch that you could check out (nothing to see yet) [here](https://github.com/thesbros/launcher/tree/feature/design).

Amit, why are we not going to use Materialize/Bootstrap? Materialize has a nice grid system that would be handy and you could create a custom .css file and strip all unnecessary parts from Materialize. This means when you need to, you can consult the docs for Materialize and add the necessary components. Personally I think Materialize would be a great place to start, it doesn't need to be entirely from scratch. It also means that we can have a nice design to work with while building up core functionality.

**Comment by pharno** [comment]
allright, thanks for clarifying. Originally I understood that you wanted to finalize the functionality before working on the styling which seemed odd to me. English is hard sometimes (for non natives at least).

And yes, that's materialize. I just wanted something which worked, and also looked halfway decent, and I like the Material look, so I took it.

@Rob-- Sounds good

**Comment by Rob--** [comment]
@pharno that's kind of what's happening - Amit is developing the design on a different branch and merging the core functionality. However, I believe we're keeping the develop branch style-less.

**Comment by amitkparekh** [comment]
@rob I think using the grid is okay, but I've grown fonder of Bootstraps grid. But that doesn't matter, I'll use one of them. 

My concern with Materialize is Material design. I love it, don't get me wrong, but in past designs I've had people tell me they hate material design and they don't like it. With this, I have to make sure we steer clear of Material. Use some principles, sure, but it can't be at all obvious. 

I will be using Materialize for some features but modifying it heavily. Maybe the same with Bootstrap

And the develop branch will only be styleless for now, until we have a design done.

**Pull request closed without merging**
